### ISSUE TITLE
Overview - An image blog

### ISSUE THREAD

**Issue by hiho-** [mdipierro/web2py-book#65]
I think that un-match line number about the description and the code.
Please see following.

Line7 -> ok
Line8 -> Line6
Line9 -> Line8
Line10 -> Line9
Line11 -> Line10 

thanks.

---

http://www.web2py.com/books/default/chapter/29/03#An-image-blog

Notice the following statements:
- **Line 7** creates an insert form SQLFORM for the `db.post` table using only the specified fields.
- **Line 8** sets the value for the reference field, which is not part of the input form because it is not in the list of fields specified above.
- **Line 9** processes the submitted form (the submitted form variables are in `request.vars`) within the current session (the session is used to prevent double submissions, and to enforce navigation). If the submitted form variables are validated, the new comment is inserted in the `db.post` table; otherwise the form is modified to include error messages (for example, if the author's email address is invalid). This is all done in **line 9**!.
- **Line 10** is only executed if the form is accepted, after the record is inserted into the database table. `response.flash` is a web2py variable that is displayed in the views and used to notify the visitor that something happened.
- **Line 11** selects all comments that reference the current image.

---

``` python
def index():
    images = db().select(db.image.ALL, orderby=db.image.title)
    return dict(images=images)

def show():
    image = db.image(request.args(0,cast=int)) or redirect(URL('index'))
    db.post.image_id.default = image.id
    form = SQLFORM(db.post)
    if form.process().accepted:
        response.flash = 'your comment is posted'
    comments = db(db.post.image_id==image.id).select()
    return dict(image=image, comments=comments, form=form)

def download():
    return response.download(request, db)
```

**Comment by rogererens** [comment]
Assuming 'def index()' is on line 1 and 'def show()' is on line 5, I think the line numbers in the 'Notice the following statements' section need to be increased by 1 (partly undoing the commit by Tim).

I'd also appreciate an explanation on why 'db.post.image_id.default' is used instead of 'db.post.image_id'.

Finally, the note 'The "download" action is already defined in the "default.py" controller of the scaffolding application' would be more appropriately placed directly following the code snippet, imho. At the current position it is too little, too late.
